version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=./points/__init__.py
      - FLASK_ENV=development
      - PYTHONPATH=.